# Generated by Django 4.2.1 on 2023-05-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearch', '0003_alter_listing_unique_together_remove_listing_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='application',
            name='job_listing',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='company',
        ),
        migrations.DeleteModel(
            name='Listing',
        ),
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='savedjob',
            name='job_listing',
        ),
        migrations.AddField(
            model_name='savedjob',
            name='category',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='savedjob',
            name='company',
            field=models.CharField(default='Undefined', max_length=100),
        ),
        migrations.AddField(
            model_name='savedjob',
            name='description',
            field=models.CharField(default='', max_length=505),
        ),
        migrations.AddField(
            model_name='savedjob',
            name='listing_id',
            field=models.CharField(default='Default ID', max_length=100),
        ),
        migrations.AddField(
            model_name='savedjob',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='savedjob',
            name='redirect_url',
            field=models.CharField(default='', max_length=160),
        ),
        migrations.AddField(
            model_name='savedjob',
            name='salary_max',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='savedjob',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='JobListing',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
