# Generated by Django 4.2.1 on 2023-05-26 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearch', '0004_remove_application_applicant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedjob',
            name='description',
            field=models.TextField(),
        ),
    ]
